version: "1.1"

services:
  node:
    container_name: plan1
    restart: always
    image: oscarali/plan1-image
    ports:
      - 3003:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - plan1_network

    command: bash -c "npm install && npm run dev"

networks:
  plan1_network:
    driver: bridge
